apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    id: 01HD6MCMV9HEFJMSGZ9E81MESN
    name: example-configuration-simple
spec:
    contentType: text/yaml
    measurementInterval: ""
    sources:
        - id: 01HD6MCMV9HEFJMSGZ9FXV7B6M
          name: example-host-custom
    destinations:
        - id: 01HD6MCMVEAQVAVCCCN5ENJGSQ
          name: example-grafana
    selector:
        matchLabels:
            configuration: example-configuration-simple
status:
    rollout:
        name: ""
        status: 4
        options:
            startAutomatically: true
            rollbackOnFailure: false
            phaseAgentCount:
                initial: 1
                multiplier: 1
                maximum: 1
            maxErrors: 0
        phase: 0
        progress:
            completed: 0
            errors: 0
            pending: 0
            waiting: 0
        startedAt: 2024-05-09T17:40:34.492233421Z
        stages: []
        stage: 0
    currentVersion: 1
    pendingVersion: 1
    latest: true
    pending: true
    current: true
