apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    id: k8s-node
    name: k8s-node
spec:
    contentType: ""
    measurementInterval: ""
    sources:
        - id: 01HMS8ERRSFYE4KGQVQ2ZXXDZK
          type: k8s_container
          parameters:
            - name: cluster_name
              value: stage2
            - name: log_source
              value: file
            - name: file_path
              value:
                - /var/log/containers/*.log
            - name: exclude_file_path
              value:
                - /var/log/containers/observiq-*-collector-*
                - /var/log/containers/bindplane-*-agent-*
            - name: journald_path
              value: ""
            - name: start_at
              value: end
        - id: 01HMS8ERRSFYE4KGQVQ8DQC5X0
          type: k8s_kubelet
          parameters:
            - name: cluster_name
              value: stage2
            - name: metric_groups
              value:
                - node
                - pod
                - container
                - volume
            - name: collection_interval
              value: 30
    destinations:
        - id: 01HMS8HBK216AD6V30GKX968XK
          name: bindplane-gateway-agent
    selector:
        matchLabels:
            configuration: k8s-node
status:
    rollout:
        name: ""
        status: 4
        options:
            startAutomatically: true
            rollbackOnFailure: false
            phaseAgentCount:
                initial: 1
                multiplier: 1
                maximum: 1
            maxErrors: 0
        phase: 0
        progress:
            completed: 0
            errors: 0
            pending: 0
            waiting: 0
        startedAt: 2024-05-09T17:40:34.899811727Z
        stages: []
        stage: 0
    currentVersion: 2
    pendingVersion: 2
    latest: true
    pending: true
    current: true
