---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: bindplane-gateway-agent
    name: bindplane-gateway-agent
spec:
    type: otlp_grpc
    parameters:
        - name: hostname
          value: bindplane-gateway-agent.bindplane-agent.svc.cluster.local
        - name: grpc_port
          value: 4317
        - name: http_port
          value: 4318
        - name: protocol
          value: grpc
        - name: headers
          value: {}
        - name: http_compression
          value: gzip
        - name: grpc_compression
          value: gzip
        - name: enable_tls
          value: false
        - name: insecure_skip_verify
          value: false
        - name: ca_file
          value: ""
        - name: mutual_tls
          value: false
        - name: cert_file
          value: ""
        - name: key_file
          value: ""
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: coralogix
    name: coralogix
spec:
    type: coralogix
    parameters:
        - name: private_key
          value: (sensitive)
          sensitive: true
        - name: application_name
          value: bindplane-test
        - name: subsystem_name
          value: test
        - name: region
          value: USA1
        - name: domain
          value: ""
        - name: resource_attributes
          value: true
        - name: application_name_attributes
          value: []
        - name: subsystem_name_attributes
          value: []
        - name: enable_metrics
          value: true
        - name: enable_logs
          value: true
        - name: enable_traces
          value: true
        - name: timeout
          value: 5
        - name: compression
          value: gzip
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: elasticsearch-internal
    name: elasticsearch-internal
spec:
    type: elasticsearch
    parameters:
        - name: enable_elastic_cloud
          value: false
        - name: endpoints
          value:
            - https://es-0.corp.net:9200
            - https://es-1.corp.net:9200
        - name: cloudid
          value: ""
        - name: enable_logs
          value: true
        - name: logs_index
          value: logs-generic-default
        - name: enable_traces
          value: true
        - name: traces_index
          value: traces-generic-default
        - name: pipeline
          value: ""
        - name: enable_auth
          value: false
        - name: auth_type
          value: basic
        - name: user
          value: ""
        - name: password
          value: (sensitive)
          sensitive: true
        - name: api_key
          value: (sensitive)
          sensitive: true
        - name: configure_tls
          value: false
        - name: insecure_skip_verify
          value: false
        - name: ca_file
          value: ""
        - name: mutual_tls
          value: false
        - name: cert_file
          value: ""
        - name: key_file
          value: ""
        - name: retry_on_failure_enabled
          value: true
        - name: num_workers
          value: 0
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: prometheus-internal
    name: prometheus-internal
spec:
    type: prometheus_remote_write
    parameters:
        - name: hostname
          value: prom-prod.corp.net
        - name: port
          value: 9009
        - name: path
          value: /api/v1/write
        - name: add_unit_and_type
          value: true
        - name: namespace
          value: ""
        - name: compression
          value: gzip
        - name: enable_resource_to_telemetry_conversion
          value: true
        - name: headers
          value: {}
        - name: external_labels
          value: {}
        - name: enable_tls
          value: false
        - name: strict_tls_verify
          value: false
        - name: ca_file
          value: ""
        - name: mutual_tls
          value: false
        - name: cert_file
          value: ""
        - name: key_file
          value: ""
        - name: enable_write_ahead_log
          value: false
        - name: wal_storage_path
          value: prometheus_rw
        - name: wal_buffer_size
          value: 300
        - name: wal_truncate_frequency
          value: 60
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
status:
    latest: true
