name: CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  # Allow action to write raw configs back to the repository.
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bindplane_versions:
          - 1.40.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Runner IP
        run: echo "MAIN_IP=$(ip addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | cut -f1 -d'/' | head -n 1)" >> $GITHUB_ENV

      - name: Print Runner IP
        run: echo $MAIN_IP

      - name: Pull BindPlane
        run: docker pull ghcr.io/observiq/bindplane-ee:${{ matrix.bindplane_versions }}

      - name: Start BindPlane
        run: |
          docker run \
            -d \
            --name bindplane \
            -e BINDPLANE_USERNAME=admin \
            -e BINDPLANE_PASSWORD=admin \
            -e BINDPLANE_REMOTE_URL=http://${MAIN_IP}:3001 \
            -e BINDPLANE_SESSION_SECRET=2c23c9d3-850f-4062-a5c8-3f9b814ae144 \
            -e BINDPLANE_SECRET_KEY=8a5353f7-bbf4-4eea-846d-a6d54296b781 \
            -e BINDPLANE_LOG_OUTPUT=stdout \
            -e BINDPLANE_ACCEPT_EULA=true \
            -p 3001:3001 \
            ghcr.io/observiq/bindplane-ee:${{ matrix.bindplane_versions }}

      - name: Run BindPlane Action
        uses: jsirianni/bindplane-op-action@dev
        with:
          remote_url: ${{ secrets.BINDPLANE_REMOTE_URL }}
          api_key: ${{ secrets.BINDPLANE_SECRET_KEY }}
          destination_path: ./resources/destinations/resource.yaml
          configuration_path: ./resources/configurations/resource.yaml
          configuration_output_dir: otel
          configuration_output_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Container Logs
        if: always()
        run: docker logs bindplane
