name: CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  # Allow action to write raw configs back to the repository.
  contents: write

# Run commits in order to prevent out of order write back commits.
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bindplane_versions:
          - 1.40.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run BindPlane Action
        uses: observIQ/bindplane-op-action@dev
        with:
          bindplane_remote_url: ${{ secrets.BINDPLANE_REMOTE_URL }}
          bindplane_api_key: ${{ secrets.BINDPLANE_SECRET_KEY }}
          destination_path: ./resources/destinations/resource.yaml
          configuration_path: ./resources/configurations/resource.yaml
          configuration_output_dir: otel
          target_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
